### ISSUE TITLE
Support ignoring (not removing) certain comments with the minifier

### ISSUE THREAD

**Issue by sgmeyer** [auth0/webtask-bundle#19]
I have a large webtask that exceeds the maximum file size, mainly due to some ejs templates.  I can't minify the webtask because I am using heredoc for my ejs templates.  

function view() {
/*
 <html><body></body></html>
*/
}

Once minified the view is gone.  I tried `/*!` to tell the minifier to keep the comment block.  Is there a way to tell the minifier leave some comments alone?

**Comment by ggoodman** [comment]
@sgmeyer would you be willing to try with [ES2015 Template Literals](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals) (aka backticks `` ` ``) instead of heredocs?

Example:
```js
const tpl = `
<h1>Hello world</h1>
`;
```

Supporting a variety of different compilation / transpilation permutations and combinations is unsustainable, so we prefer to stick with a very simple subset.

**Comment by sgmeyer** [comment]
@ggoodman yup I can do that.  I will also go through our sample rules and fix those examples too. I think a few of them are already using heredoc.
